# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          Tale
paginate:       5
baseurl:        apharrington.github.io
url:            "https://apharrington.github.io"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         AP Harrington
  url:          http://apharrington.github.io
  email:        apaigeharrington@gmail.com

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/apharrington.github.io

# Gems
gems:
  - jekyll-paginate
